// Hand-written trivia. Facts are as of the 2025/26 season; nothing here depends
// on results after mid-2026. Format: [category, question, correct, wrong, wrong, wrong]
export const TRIVIA = [
  // World Cup
  ['World Cup', 'Who won the 2022 World Cup in Qatar?', 'Argentina', 'France', 'Croatia', 'Brazil'],
  ['World Cup', 'Who won the 2018 World Cup?', 'France', 'Croatia', 'Belgium', 'England'],
  ['World Cup', 'Who won the 2014 World Cup?', 'Germany', 'Argentina', 'Netherlands', 'Brazil'],
  ['World Cup', 'Who won the 2010 World Cup?', 'Spain', 'Netherlands', 'Germany', 'Uruguay'],
  ['World Cup', 'Who won the 2006 World Cup?', 'Italy', 'France', 'Germany', 'Portugal'],
  ['World Cup', 'Who won the 2002 World Cup?', 'Brazil', 'Germany', 'Turkey', 'South Korea'],
  ['World Cup', 'Who scored the winner in the 2014 World Cup final?', 'Mario Götze', 'Thomas Müller', 'Miroslav Klose', 'André Schürrle'],
  ['World Cup', 'Who scored the winner in the 2010 World Cup final?', 'Andrés Iniesta', 'David Villa', 'Xavi', 'Fernando Torres'],
  ['World Cup', 'Who scored a hat-trick in the 2022 World Cup final?', 'Kylian Mbappé', 'Lionel Messi', 'Julián Álvarez', 'Olivier Giroud'],
  ['World Cup', 'Who won the Golden Ball at the 2022 World Cup?', 'Lionel Messi', 'Kylian Mbappé', 'Luka Modrić', 'Achraf Hakimi'],
  ['World Cup', 'Who won the Golden Boot at the 2022 World Cup?', 'Kylian Mbappé', 'Lionel Messi', 'Olivier Giroud', 'Julián Álvarez'],
  ['World Cup', 'Who won Best Young Player at the 2022 World Cup?', 'Enzo Fernández', 'Jude Bellingham', 'Gavi', 'Joško Gvardiol'],
  ['World Cup', 'Who won the Golden Ball at the 2018 World Cup?', 'Luka Modrić', 'Kylian Mbappé', 'Antoine Griezmann', 'Eden Hazard'],
  ['World Cup', 'Who won the Golden Boot at the 2018 World Cup?', 'Harry Kane', 'Antoine Griezmann', 'Romelu Lukaku', 'Cristiano Ronaldo'],
  ['World Cup', 'Which African nation reached the 2022 World Cup semi-finals?', 'Morocco', 'Senegal', 'Cameroon', 'Ghana'],
  ['World Cup', 'Who hosted and won the first World Cup in 1930?', 'Uruguay', 'Argentina', 'Italy', 'Brazil'],
  ['World Cup', 'Zidane was sent off in the 2006 final for headbutting who?', 'Marco Materazzi', 'Fabio Cannavaro', 'Gennaro Gattuso', 'Andrea Pirlo'],
  ['World Cup', 'Maradona\'s "Hand of God" goal in 1986 was against which country?', 'England', 'West Germany', 'Belgium', 'Italy'],
  ['World Cup', 'Germany beat which team 7–1 in the 2014 World Cup semi-final?', 'Brazil', 'Argentina', 'Netherlands', 'France'],
  ['World Cup', 'Which three countries co-hosted the 2026 World Cup?', 'USA, Canada & Mexico', 'USA, Mexico & Costa Rica', 'Canada, USA & Jamaica', 'Mexico, USA & Panama'],
  ['World Cup', 'How many World Cups had Brazil won before 2026?', '5', '4', '6', '3'],
  ['World Cup', 'Who was Argentina\'s goalkeeper in the 2022 final shootout win?', 'Emiliano Martínez', 'Franco Armani', 'Gerónimo Rulli', 'Sergio Romero'],

  // Euros & Copa
  ['Euros', 'Who won Euro 2024?', 'Spain', 'England', 'France', 'Netherlands'],
  ['Euros', 'What was the score in the Euro 2024 final?', 'Spain 2–1 England', 'Spain 1–0 England', 'Spain 3–1 England', 'Spain 2–0 England'],
  ['Euros', 'Who won Euro 2020 (played in 2021)?', 'Italy', 'England', 'Spain', 'Denmark'],
  ['Euros', 'Who won Euro 2016?', 'Portugal', 'France', 'Germany', 'Wales'],
  ['Euros', 'Who scored the extra-time winner in the Euro 2016 final?', 'Éder', 'Cristiano Ronaldo', 'Nani', 'Ricardo Quaresma'],
  ['Euros', 'Which underdog won Euro 2004?', 'Greece', 'Czech Republic', 'Denmark', 'Turkey'],
  ['Euros', 'Which country hosted Euro 2024?', 'Germany', 'France', 'England', 'Italy'],
  ['Euros', 'Who won Young Player of the Tournament at Euro 2024?', 'Lamine Yamal', 'Jamal Musiala', 'Arda Güler', 'Kobbie Mainoo'],
  ['Euros', 'Who was named Player of the Tournament at Euro 2024?', 'Rodri', 'Lamine Yamal', 'Dani Olmo', 'Nico Williams'],
  ['Euros', 'Which country has won the most European Championships?', 'Spain', 'Germany', 'France', 'Italy'],
  ['Copa', 'Who won the 2024 Copa América?', 'Argentina', 'Colombia', 'Uruguay', 'Brazil'],
  ['Copa', 'Who won the 2021 Copa América, beating Brazil at the Maracanã?', 'Argentina', 'Chile', 'Colombia', 'Peru'],
  ['Copa', 'Which nation has won the most Copa América titles?', 'Argentina', 'Uruguay', 'Brazil', 'Chile'],
  ['AFCON', 'Who won the Africa Cup of Nations played in early 2024?', 'Ivory Coast', 'Nigeria', 'South Africa', 'Morocco'],

  // Champions League
  ['UCL', 'Who won the 2024–25 Champions League?', 'PSG', 'Inter', 'Arsenal', 'Barcelona'],
  ['UCL', 'What was the score in the 2025 Champions League final?', 'PSG 5–0 Inter', 'PSG 2–0 Inter', 'PSG 3–1 Inter', 'PSG 4–1 Inter'],
  ['UCL', 'Who won the 2023–24 Champions League?', 'Real Madrid', 'Dortmund', 'Bayern', 'PSG'],
  ['UCL', 'Who won the 2022–23 Champions League?', 'Man City', 'Inter', 'Real Madrid', 'AC Milan'],
  ['UCL', 'Who scored the only goal of the 2023 Champions League final?', 'Rodri', 'Erling Haaland', 'Kevin De Bruyne', 'İlkay Gündoğan'],
  ['UCL', 'Who scored the winner in the 2021 Champions League final?', 'Kai Havertz', 'Mason Mount', 'Timo Werner', 'N\'Golo Kanté'],
  ['UCL', 'Who scored the winner for Bayern in the 2020 Champions League final vs PSG?', 'Kingsley Coman', 'Robert Lewandowski', 'Thomas Müller', 'Serge Gnabry'],
  ['UCL', 'Who did Liverpool beat in the 2019 Champions League final?', 'Tottenham', 'Real Madrid', 'Barcelona', 'Ajax'],
  ['UCL', 'Which club has won the most European Cups / Champions Leagues?', 'Real Madrid', 'AC Milan', 'Bayern', 'Liverpool'],
  ['UCL', 'Who managed Real Madrid to three straight Champions Leagues (2016–18)?', 'Zinedine Zidane', 'Carlo Ancelotti', 'José Mourinho', 'Rafael Benítez'],
  ['UCL', 'Liverpool\'s 2005 "Miracle of Istanbul" came against which team?', 'AC Milan', 'Juventus', 'Chelsea', 'Barcelona'],
  ['UCL', 'Gareth Bale\'s overhead kick in the 2018 final came against which club?', 'Liverpool', 'Juventus', 'Atlético Madrid', 'Bayern'],
  ['UCL', 'Who is the Champions League\'s all-time top scorer?', 'Cristiano Ronaldo', 'Lionel Messi', 'Robert Lewandowski', 'Karim Benzema'],
  ['UCL', 'Who won the 2012 Champions League in Munich?', 'Chelsea', 'Bayern', 'Barcelona', 'Real Madrid'],
  ['UCL', 'Man United beat which team with two stoppage-time goals in the 1999 final?', 'Bayern', 'Juventus', 'Barcelona', 'Valencia'],
  ['UCL', 'Who managed Porto to Champions League glory in 2004?', 'José Mourinho', 'André Villas-Boas', 'Fernando Santos', 'Jesualdo Ferreira'],
  ['UCL', 'Which of these players won SIX Champions Leagues with Real Madrid?', 'Luka Modrić', 'Cristiano Ronaldo', 'Sergio Ramos', 'Karim Benzema'],
  ['UCL', 'Who managed PSG to their 2024–25 treble?', 'Luis Enrique', 'Mauricio Pochettino', 'Thomas Tuchel', 'Christophe Galtier'],
  ['UCL', 'Sergio Ramos\' 93rd-minute equaliser in the 2014 final came against who?', 'Atlético Madrid', 'Juventus', 'Liverpool', 'Bayern'],
  ['Club WC', 'Who won the expanded 2025 FIFA Club World Cup?', 'Chelsea', 'PSG', 'Real Madrid', 'Bayern'],

  // Ballon d'Or
  ['Ballon d\'Or', 'Who won the 2025 Ballon d\'Or?', 'Ousmane Dembélé', 'Lamine Yamal', 'Vitinha', 'Mohamed Salah'],
  ['Ballon d\'Or', 'Who won the 2024 Ballon d\'Or?', 'Rodri', 'Vinícius Júnior', 'Jude Bellingham', 'Dani Carvajal'],
  ['Ballon d\'Or', 'Who won the 2023 Ballon d\'Or?', 'Lionel Messi', 'Erling Haaland', 'Kylian Mbappé', 'Kevin De Bruyne'],
  ['Ballon d\'Or', 'Who won the 2022 Ballon d\'Or?', 'Karim Benzema', 'Sadio Mané', 'Kevin De Bruyne', 'Robert Lewandowski'],
  ['Ballon d\'Or', 'Who broke the Messi–Ronaldo streak by winning the 2018 Ballon d\'Or?', 'Luka Modrić', 'Antoine Griezmann', 'Kylian Mbappé', 'Mohamed Salah'],
  ['Ballon d\'Or', 'How many Ballon d\'Ors has Lionel Messi won?', '8', '7', '6', '9'],
  ['Ballon d\'Or', 'How many Ballon d\'Ors has Cristiano Ronaldo won?', '5', '4', '6', '3'],
  ['Ballon d\'Or', 'Which defender won the 2006 Ballon d\'Or?', 'Fabio Cannavaro', 'Paolo Maldini', 'John Terry', 'Lilian Thuram'],
  ['Ballon d\'Or', 'Who won the 2007 Ballon d\'Or?', 'Kaká', 'Cristiano Ronaldo', 'Lionel Messi', 'Didier Drogba'],
  ['Ballon d\'Or', 'Who is the only African player to win the Ballon d\'Or?', 'George Weah', 'Didier Drogba', 'Samuel Eto\'o', 'Mohamed Salah'],
  ['Ballon d\'Or', 'Who won the 2024 Kopa Trophy for the best young player?', 'Lamine Yamal', 'Arda Güler', 'Kobbie Mainoo', 'Pau Cubarsí'],

  // Premier League
  ['Premier League', 'Who won the 2024–25 Premier League?', 'Liverpool', 'Arsenal', 'Man City', 'Chelsea'],
  ['Premier League', 'Who won the 2023–24 Premier League?', 'Man City', 'Arsenal', 'Liverpool', 'Aston Villa'],
  ['Premier League', 'Who is the Premier League\'s all-time top scorer?', 'Alan Shearer', 'Harry Kane', 'Wayne Rooney', 'Andy Cole'],
  ['Premier League', 'Which club has won the most Premier League titles?', 'Man United', 'Man City', 'Chelsea', 'Arsenal'],
  ['Premier League', 'In which season did Arsenal go unbeaten ("The Invincibles")?', '2003–04', '2001–02', '2004–05', '1997–98'],
  ['Premier League', 'In which season did Leicester win the Premier League?', '2015–16', '2014–15', '2016–17', '2013–14'],
  ['Premier League', 'Who managed Leicester to the 2015–16 title?', 'Claudio Ranieri', 'Brendan Rodgers', 'Nigel Pearson', 'Craig Shakespeare'],
  ['Premier League', 'How many league goals did Haaland score in his record 2022–23 season?', '36', '34', '32', '38'],
  ['Premier League', 'Agüero\'s famous 93:20 title winner in 2012 came against who?', 'QPR', 'Sunderland', 'Stoke City', 'Newcastle'],
  ['Premier League', 'Who holds the record for most Premier League assists?', 'Ryan Giggs', 'Kevin De Bruyne', 'Cesc Fàbregas', 'Frank Lampard'],
  ['Premier League', 'Who has kept the most Premier League clean sheets?', 'Petr Čech', 'David de Gea', 'Edwin van der Sar', 'David James'],
  ['Premier League', 'How many Premier League goals did Mohamed Salah score in 2024–25?', '29', '27', '32', '25'],
  ['Premier League', 'Who scored the fastest hat-trick in Premier League history?', 'Sadio Mané', 'Robbie Fowler', 'Sergio Agüero', 'Jermain Defoe'],
  ['Premier League', 'Before Liverpool, which club did Arne Slot manage?', 'Feyenoord', 'AZ', 'Ajax', 'PSV'],

  // Leagues & clubs
  ['Leagues', 'Who won La Liga in 2024–25?', 'Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club'],
  ['Leagues', 'Who won Serie A in 2024–25?', 'Napoli', 'Inter', 'Atalanta', 'Juventus'],
  ['Leagues', 'Which club went unbeaten to win the 2023–24 Bundesliga?', 'Leverkusen', 'Bayern', 'Stuttgart', 'Dortmund'],
  ['Leagues', 'Who managed Leverkusen\'s unbeaten 2023–24 Bundesliga season?', 'Xabi Alonso', 'Julian Nagelsmann', 'Thomas Tuchel', 'Edin Terzić'],
  ['Leagues', 'Who managed Napoli to the 2024–25 Serie A title?', 'Antonio Conte', 'Luciano Spalletti', 'Carlo Ancelotti', 'Maurizio Sarri'],
  ['Leagues', 'How many Bundesliga goals did Lewandowski score in 2020–21 to beat Gerd Müller\'s record?', '41', '40', '38', '43'],
  ['Leagues', 'Which club has won the most Serie A titles?', 'Juventus', 'Inter', 'AC Milan', 'Roma'],
  ['Leagues', 'Which club has won the most Bundesliga titles?', 'Bayern', 'Dortmund', 'Gladbach', 'Hamburg'],

  // Stadiums
  ['Stadiums', 'Which club plays at Anfield?', 'Liverpool', 'Everton', 'Man United', 'Newcastle'],
  ['Stadiums', 'Which club plays at the Santiago Bernabéu?', 'Real Madrid', 'Atlético Madrid', 'Barcelona', 'Sevilla'],
  ['Stadiums', 'Which club plays at Signal Iduna Park?', 'Dortmund', 'Bayern', 'Schalke', 'Leverkusen'],
  ['Stadiums', 'Which club plays at the Allianz Arena?', 'Bayern', 'Juventus', 'Dortmund', 'RB Leipzig'],
  ['Stadiums', 'Which two clubs share the San Siro?', 'Inter & AC Milan', 'Juventus & Torino', 'Roma & Lazio', 'Genoa & Sampdoria'],
  ['Stadiums', 'Which club plays at the Parc des Princes?', 'PSG', 'Marseille', 'Lyon', 'Monaco'],
  ['Stadiums', 'Which club plays at St James\' Park?', 'Newcastle', 'Sunderland', 'Leeds', 'Aston Villa'],
  ['Stadiums', 'Which club plays at La Bombonera?', 'Boca Juniors', 'River Plate', 'Racing Club', 'Independiente'],
  ['Stadiums', 'Which club plays at Estádio da Luz?', 'Benfica', 'Porto', 'Sporting CP', 'Braga'],
  ['Stadiums', 'Which club\'s ground is nicknamed "The Theatre of Dreams"?', 'Man United', 'Liverpool', 'Arsenal', 'Real Madrid'],
  ['Stadiums', 'Which club plays at the Metropolitano?', 'Atlético Madrid', 'Real Madrid', 'Getafe', 'Valencia'],

  // Nicknames & derbies
  ['Nicknames', 'Which club is known as "The Red Devils"?', 'Man United', 'Liverpool', 'Arsenal', 'Nottingham Forest'],
  ['Nicknames', 'Which club is known as "The Gunners"?', 'Arsenal', 'West Ham', 'Tottenham', 'Chelsea'],
  ['Nicknames', 'Which club is known as "La Vecchia Signora" (The Old Lady)?', 'Juventus', 'AC Milan', 'Inter', 'Roma'],
  ['Nicknames', 'Which club is known as "The Toffees"?', 'Everton', 'Burnley', 'Wolves', 'Fulham'],
  ['Nicknames', 'Which club is known as "The Magpies"?', 'Newcastle', 'Crystal Palace', 'Brighton', 'Leeds'],
  ['Nicknames', 'Which club is known as "Die Werkself"?', 'Leverkusen', 'Wolfsburg', 'Bayern', 'Stuttgart'],
  ['Nicknames', 'Which club is known as "The Hammers"?', 'West Ham', 'Brentford', 'Wolves', 'Fulham'],
  ['Nicknames', 'Which player is nicknamed "La Pulga" (The Flea)?', 'Lionel Messi', 'Sergio Agüero', 'Ángel Di María', 'Paulo Dybala'],
  ['Nicknames', 'Which player was nicknamed "El Niño"?', 'Fernando Torres', 'Raúl', 'David Villa', 'Fernando Morientes'],
  ['Nicknames', 'Which player was nicknamed "Il Divin Codino" (The Divine Ponytail)?', 'Roberto Baggio', 'Alessandro Del Piero', 'Andrea Pirlo', 'Francesco Totti'],
  ['Nicknames', 'Which player is nicknamed "El Pistolero"?', 'Luis Suárez', 'Edinson Cavani', 'Diego Forlán', 'Radamel Falcao'],
  ['Nicknames', 'Which manager called himself "The Special One"?', 'José Mourinho', 'Pep Guardiola', 'Jürgen Klopp', 'Carlo Ancelotti'],
  ['Nicknames', 'Who is "The Egyptian King"?', 'Mohamed Salah', 'Mohamed Elneny', 'Omar Marmoush', 'Ahmed Hegazi'],
  ['Derbies', '"El Clásico" is played between which two clubs?', 'Real Madrid & Barcelona', 'Real Madrid & Atlético', 'Barcelona & Espanyol', 'Sevilla & Real Betis'],
  ['Derbies', '"Der Klassiker" is played between which two clubs?', 'Bayern & Dortmund', 'Dortmund & Schalke', 'Bayern & 1860 Munich', 'Hamburg & Werder Bremen'],
  ['Derbies', 'The "Old Firm" derby is between which clubs?', 'Celtic & Rangers', 'Hearts & Hibernian', 'Dundee & Dundee United', 'Aberdeen & Rangers'],
  ['Derbies', 'The "Superclásico" is between which clubs?', 'Boca Juniors & River Plate', 'Flamengo & Fluminense', 'Racing & Independiente', 'Peñarol & Nacional'],
  ['Derbies', '"Le Classique" is between which clubs?', 'PSG & Marseille', 'Lyon & Saint-Étienne', 'PSG & Lyon', 'Monaco & Nice'],
  ['Derbies', 'The "Derby della Madonnina" is between which clubs?', 'Inter & AC Milan', 'Roma & Lazio', 'Juventus & Torino', 'Napoli & Roma'],

  // Records & legends
  ['Records', 'Who has scored the most men\'s international goals?', 'Cristiano Ronaldo', 'Lionel Messi', 'Ali Daei', 'Sunil Chhetri'],
  ['Records', 'Who is Arsenal\'s all-time top scorer?', 'Thierry Henry', 'Ian Wright', 'Robin van Persie', 'Dennis Bergkamp'],
  ['Records', 'Who is Man United\'s all-time top scorer?', 'Wayne Rooney', 'Bobby Charlton', 'Denis Law', 'Ryan Giggs'],
  ['Records', 'Who is Real Madrid\'s all-time top scorer?', 'Cristiano Ronaldo', 'Raúl', 'Karim Benzema', 'Alfredo Di Stéfano'],
  ['Records', 'Who is Chelsea\'s all-time top scorer?', 'Frank Lampard', 'Didier Drogba', 'Bobby Tambling', 'Eden Hazard'],
  ['Records', 'Who is Tottenham\'s all-time top scorer?', 'Harry Kane', 'Jimmy Greaves', 'Son Heung-min', 'Jermain Defoe'],
  ['Records', 'Who is Liverpool\'s all-time top scorer?', 'Ian Rush', 'Mohamed Salah', 'Roger Hunt', 'Steven Gerrard'],
  ['Records', 'Who is Bayern\'s all-time top scorer?', 'Gerd Müller', 'Robert Lewandowski', 'Karl-Heinz Rummenigge', 'Thomas Müller'],
  ['Records', 'Neymar\'s world-record move to PSG in 2017 cost roughly how much?', '€222 million', '€180 million', '€150 million', '€250 million'],
  ['Records', 'In which country was Erling Haaland born?', 'England', 'Norway', 'Germany', 'Sweden'],

  // Transfers
  ['Transfers', 'Which club did Jude Bellingham leave to join Real Madrid?', 'Dortmund', 'Birmingham', 'Bayern', 'RB Leipzig'],
  ['Transfers', 'Which club did Florian Wirtz join in summer 2025?', 'Liverpool', 'Bayern', 'Man City', 'Real Madrid'],
  ['Transfers', 'Where did Kevin De Bruyne go after leaving Man City in 2025?', 'Napoli', 'Inter Miami', 'Al Hilal', 'Club Brugge'],
  ['Transfers', 'Which club did Luka Modrić join in 2025?', 'AC Milan', 'Dinamo Zagreb', 'Inter Miami', 'Al Nassr'],
  ['Transfers', 'Which club did Trent Alexander-Arnold join in 2025?', 'Real Madrid', 'Barcelona', 'PSG', 'Bayern'],
  ['Transfers', 'Which club did Viktor Gyökeres join in 2025?', 'Arsenal', 'Man United', 'Chelsea', 'Juventus'],
  ['Transfers', 'Which club did Alexander Isak join in September 2025?', 'Liverpool', 'Arsenal', 'Chelsea', 'Barcelona'],
  ['Transfers', 'Which club did Son Heung-min join after leaving Tottenham in 2025?', 'LAFC', 'LA Galaxy', 'Al Ittihad', 'Bayern'],
  ['Transfers', 'Which MLS club did Lionel Messi join in 2023?', 'Inter Miami', 'LA Galaxy', 'LAFC', 'New York City FC'],
  ['Transfers', 'Which was Cristiano Ronaldo\'s first professional club?', 'Sporting CP', 'Benfica', 'Porto', 'Man United'],
  ['Transfers', 'Which club did Pep Guardiola manage right before Man City?', 'Bayern', 'Barcelona', 'Barcelona B', 'Al Ahli'],
  ['Transfers', 'Which club did Harry Kane join in 2023?', 'Bayern', 'Man United', 'Real Madrid', 'PSG'],
  ['Transfers', 'Which of these clubs has Cristiano Ronaldo NEVER played for?', 'Barcelona', 'Juventus', 'Sporting CP', 'Al Nassr'],
  ['Transfers', 'Which of these clubs has Zlatan Ibrahimović NEVER played for?', 'Real Madrid', 'Ajax', 'Barcelona', 'PSG'],
  ['Transfers', 'Which shirt number did Lamine Yamal take at Barcelona in 2025?', '10', '19', '9', '7'],
];
