// One-time build step: looks up each player's Wikipedia lead photo and bakes
// the Wikimedia URLs into js/photos.js, so players' browsers load images
// straight from the Wikimedia CDN instead of hammering the Wikipedia API.
//   node tools/fetch-photos.mjs
import { writeFileSync } from 'node:fs';
import { PLAYERS } from '../js/data.js';

const UA = 'BallKnowledgeQuiz/1.0 (local build script)';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function query(titles) {
  const u = 'https://en.wikipedia.org/w/api.php?action=query&prop=pageimages&piprop=thumbnail'
    + '&pithumbsize=420&redirects=1&format=json&titles=' + encodeURIComponent(titles.join('|'));
  for (let attempt = 0; attempt < 8; attempt++) {
    const res = await fetch(u, { headers: { 'User-Agent': UA } });
    if (res.status === 429) {
      const wait = (+res.headers.get('retry-after') || 30) + 2;
      console.log(`rate limited, waiting ${wait}s`);
      await sleep(wait * 1000);
      continue;
    }
    return res.json();
  }
  throw new Error('gave up');
}

const out = {};
const missing = [];
for (let i = 0; i < PLAYERS.length; i += 50) {
  const chunk = PLAYERS.slice(i, i + 50);
  const d = await query(chunk.map((p) => p.wiki));
  const map = {};
  for (const n of d.query.normalized || []) map[n.from] = n.to;
  for (const r of d.query.redirects || []) map[r.from] = r.to;
  const pages = Object.values(d.query.pages);
  for (const p of chunk) {
    let t = map[p.wiki] || p.wiki;
    t = map[t] || t;
    const pg = pages.find((x) => x.title === t);
    if (pg && pg.thumbnail) out[p.id] = pg.thumbnail.source.replace(/\?.*$/, '');
    else missing.push(`${p.name} (${p.wiki})`);
  }
  await sleep(1500);
}

writeFileSync(new URL('../js/photos.js', import.meta.url),
  '// Generated by tools/fetch-photos.mjs: Wikimedia Commons lead photos (see each file page for license).\n'
  + 'export const PHOTOS = ' + JSON.stringify(out, null, 0).replace(/","/g, '",\n"') + ';\n');
console.log(`${Object.keys(out).length} photos written`);
if (missing.length) console.log('missing:\n' + missing.join('\n'));
